# Numpy

NumPy (Numerical Python) is a fundamental Python library for scientific computing, providing powerful N-dimensional array objects (ndarray) and fast functions for numerical operations, making it essential for data science, AI, and engineering.

In [1]:
! pip install numpy

In [2]:
# import the numpy library
import numpy as np

In [36]:
lst=[1,2,3,4,5]
np.array(lst)

array([1, 2, 3, 4, 5])

In [3]:
# create a numpy array
# numpy array format: np.array(list)
arr=np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))
print(arr.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [4]:
# create a 2d array
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d)
print(arr_2d.shape) # rows and columns

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [5]:
# rehsape a numpy array
arr=np.array([1, 2, 3, 4, 5]).reshape(1,5)
print(arr.shape)
print(arr)


(1, 5)
[[1 2 3 4 5]]


In [45]:
lst=[1,2,3,4,5,6,7,9,33,45,67,34]  # 1d Array ,Total element number =12

# 12= 1x12, 2x6, 3x4, 2x3x2

d2=np.array(lst).reshape(3,4)
print(d2)
print('Array dimention: ',d2.ndim)
print('Array shape: ',d2.shape)

d3=np.array(lst).reshape(3,2,2)
print(d3)
print('Array dimention: ',d3.ndim)


[[ 1  2  3  4]
 [ 5  6  7  9]
 [33 45 67 34]]
Array dimention:  2
Array shape:  (3, 4)
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  9]]

 [[33 45]
  [67 34]]]
Array dimention:  3


In [50]:
# Arnage
np.arange(start=2,stop=200,step=2).reshape(11,9)

array([[  2,   4,   6,   8,  10,  12,  14,  16,  18],
       [ 20,  22,  24,  26,  28,  30,  32,  34,  36],
       [ 38,  40,  42,  44,  46,  48,  50,  52,  54],
       [ 56,  58,  60,  62,  64,  66,  68,  70,  72],
       [ 74,  76,  78,  80,  82,  84,  86,  88,  90],
       [ 92,  94,  96,  98, 100, 102, 104, 106, 108],
       [110, 112, 114, 116, 118, 120, 122, 124, 126],
       [128, 130, 132, 134, 136, 138, 140, 142, 144],
       [146, 148, 150, 152, 154, 156, 158, 160, 162],
       [164, 166, 168, 170, 172, 174, 176, 178, 180],
       [182, 184, 186, 188, 190, 192, 194, 196, 198]])

In [7]:
np.zeros((3,4,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [51]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# Identity Matrix
np.eye(5) # 5x5 identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Linspace
np.linspace(10,20,5) # 2.5 ,2.5

array([10. , 12.5, 15. , 17.5, 20. ])

In [11]:
# Random Numbers
np.random.rand(3,4) # 3 rows and 4 columns of random numbers between 0 and 1

array([[0.70719579, 0.26706334, 0.35492199, 0.35505376],
       [0.26915802, 0.81192115, 0.85858597, 0.93128321],
       [0.62173949, 0.20373692, 0.75424308, 0.57259219]])

In [12]:
# randn
np.random.randn(3,4) # 3 rows and 4 columns of random numbers from standard normal distribution

array([[ 0.70140445, -1.21493984,  1.89195452, -0.08992077],
       [ 0.31712875, -2.21207192, -0.69380433,  2.13122469],
       [ 1.46696854, -1.84783407,  0.62849106, -0.15091783]])

In [13]:
# Randint
np.random.randint(10,20,(3,4))

array([[19, 16, 16, 15],
       [15, 15, 16, 19],
       [16, 11, 17, 16]], dtype=int32)

In [14]:
# Attibutes of Numpy Array
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Array:\n',arr)
print('Dimensions:',arr.ndim)
print('Shape:',arr.shape)
print('Size:',arr.size)
print('Data Type:',arr.dtype)
print('Item Size (in bytes):',arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimensions: 2
Shape: (3, 3)
Size: 9
Data Type: int64
Item Size (in bytes): 8


In [57]:
# array Slicing and Indexing
arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(arr.ndim)
arr

2


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [16]:
arr[0,2]

np.int64(3)

In [17]:
arr[:,2:]

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15]])

In [18]:
arr[1:,2:4]

array([[ 8,  9],
       [13, 14]])

In [58]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
arr[0:2,1:3] # row 0,1  col 1,2

array([[2, 3],
       [7, 8]])

In [20]:
arr_1d=np.array([1,2,3,4,5,6,7,8,9,10])
arr_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
arr_1d[3:8]

array([4, 5, 6, 7, 8])

In [22]:
np.random.randint(1,4,1)

array([3], dtype=int32)

In [23]:
arr=np.array([[1,2,3,4,5,12],[6,7,8,9,10,55],[11,12,13,14,15,77],[70,77,66,54,33,43]])
arr

array([[ 1,  2,  3,  4,  5, 12],
       [ 6,  7,  8,  9, 10, 55],
       [11, 12, 13, 14, 15, 77],
       [70, 77, 66, 54, 33, 43]])

In [62]:
# Numpy Vectorized Operations
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([10,20,30,40,50,55]) 
# element wise addition
print('Addition:',arr1 + arr2)
# element wise subtraction
print('Subtraction:',arr2 - arr1)
# element wise multiplication
print('Multiplication:',arr1 * arr2)
# element wise division
print('Division:',arr2 / arr1)

Addition: [11 22 33 44 55 61]
Subtraction: [ 9 18 27 36 45 49]
Multiplication: [ 10  40  90 160 250 330]
Division: [10.         10.         10.         10.         10.          9.16666667]


In [25]:
# Implementation with 2D arrays
arr1_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2_2d=np.array([[10,20,30],[40,50,60],[70,80,90]])
print('2D Array 1:\n',arr1_2d)
print('2D Array 2:\n',arr2_2d)
# element wise addition
print('2D Addition:\n',arr1_2d + arr2_2d)

2D Array 1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
2D Array 2:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
2D Addition:
 [[11 22 33]
 [44 55 66]
 [77 88 99]]


In [26]:
# Universal Functions (ufuncs)
arr=np.array([1,2,3,4,5,9])
# square root
print('Square Root:',np.sqrt(arr))

# exponential
print('Exponential:',np.exp(arr))

# sine
print('Sine:',np.sin(arr))

# logarithm
print('Logarithm:',np.log(arr))

Square Root: [1.         1.41421356 1.73205081 2.         2.23606798 3.        ]
Exponential: [2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 8.10308393e+03]
Sine: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427  0.41211849]
Logarithm: [0.         0.69314718 1.09861229 1.38629436 1.60943791 2.19722458]


In [27]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
arr2=arr[3:7]
arr2

array([4, 5, 6, 7])

In [29]:
arr2[0]=100
arr2

array([100,   5,   6,   7])

In [30]:
arr

array([  1,   2,   3, 100,   5,   6,   7,   8,   9,  10])

In [31]:
arr3=arr.copy()
arr3

array([  1,   2,   3, 100,   5,   6,   7,   8,   9,  10])

In [32]:
# Statistical Operations for normalization 
# normalization means to have value mean 0 and standard deviation 1
data=np.array([1,2,3,4,5,6,7,8,9,10])

# calculate mean
mean=data.mean()

# calculate standard deviation
std=data.std()

# normalize the data
normalized_data=(data - mean)/std
print('Normalized Data:',normalized_data)

Normalized Data: [-1.5666989  -1.21854359 -0.87038828 -0.52223297 -0.17407766  0.17407766
  0.52223297  0.87038828  1.21854359  1.5666989 ]


In [33]:
# calculate median mean standard deviation variance
data=np.array([1,2,3,4,5,6,7,8,9,10])

median=np.median(data)
mean=np.mean(data)
std=np.std(data)
variance=np.var(data)

print('Median:',median)
print('Mean:',mean) 
print('Standard Deviation:',std)
print('Variance:',variance)

Median: 5.5
Mean: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [34]:
# logical operation with numpy arrays
arr=np.array([10,20,30,40,50,60,70,80,90,100])
# elements greater than 50
print(arr[arr > 50])

arr[(arr > 50) & (arr < 90)]

[ 60  70  80  90 100]


array([60, 70, 80])

In [35]:
arr=np.array([10,20,30,40,50,60,70,80,90,100])


arr[arr>20]


array([ 30,  40,  50,  60,  70,  80,  90, 100])