# Numpy

In [1]:
! pip install numpy

In [2]:
# import the numpy library
import numpy as np

In [7]:
# create a numpy array
# numpy array format: np.array(list)
arr=np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))
print(arr.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [10]:
# create a 2d array
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d)
print(arr_2d.shape) # rows and columns

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [15]:
# rehsape a numpy array
arr=np.array([1, 2, 3, 4, 5]).reshape(1,5)
print(arr.shape)
print(arr)


(1, 5)
[[1 2 3 4 5]]


In [21]:
# Arnage
np.arange(start=2,stop=21,step=2).reshape(2,5)

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

In [25]:
np.zeros((3,4,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [27]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
# Identity Matrix
np.eye(5) # 4x4 identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Linspace
np.linspace(10,20,5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [ ]:
# Random Numbers
np.random.rand(3,4) # 3 rows and 4 columns of random numbers between 0 and 1

array([[0.85795642, 0.76387573, 0.4587883 , 0.93441733],
       [0.82450305, 0.18586368, 0.41811902, 0.03200974],
       [0.47035727, 0.56403693, 0.21425517, 0.88719609]])

In [35]:
# randn
np.random.randn(3,4) # 3 rows and 4 columns of random numbers from standard normal distribution

array([[ 1.05756141,  0.24806459,  1.37065426,  0.66655146],
       [ 0.4583806 ,  0.71746048, -0.44279996, -0.88859406],
       [ 0.21105983, -0.96065457,  0.43826904,  1.60025574]])

In [38]:
# Randint
np.random.randint(10,20,(3,4))

array([[16, 12, 13, 15],
       [16, 12, 15, 15],
       [17, 13, 12, 13]], dtype=int32)

In [39]:
# Attibutes of Numpy Array
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Array:\n',arr)
print('Dimensions:',arr.ndim)
print('Shape:',arr.shape)
print('Size:',arr.size)
print('Data Type:',arr.dtype)
print('Item Size (in bytes):',arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimensions: 2
Shape: (3, 3)
Size: 9
Data Type: int64
Item Size (in bytes): 8


In [42]:
# array Slicing and Indexing
arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(arr.ndim)
arr

2


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
arr[0,2]

np.int64(3)

In [62]:
arr[:,2:]

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15]])

In [58]:
arr[1:,2:4]

array([[ 8,  9],
       [13, 14]])

In [60]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [43]:
arr_1d=np.array([1,2,3,4,5,6,7,8,9,10])
arr_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
arr_1d[3:8]

array([4, 5, 6, 7, 8])