# Numpy

In [24]:
! pip install numpy

In [25]:
# import the numpy library
import numpy as np

In [26]:
# create a numpy array
# numpy array format: np.array(list)
arr=np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))
print(arr.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [27]:
# create a 2d array
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d)
print(arr_2d.shape) # rows and columns

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [28]:
# rehsape a numpy array
arr=np.array([1, 2, 3, 4, 5]).reshape(1,5)
print(arr.shape)
print(arr)


(1, 5)
[[1 2 3 4 5]]


In [29]:
# Arnage
np.arange(start=2,stop=21,step=2).reshape(2,5)

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

In [30]:
np.zeros((3,4,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [31]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# Identity Matrix
np.eye(5) # 5x5 identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
# Linspace
np.linspace(10,20,5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [34]:
# Random Numbers
np.random.rand(3,4) # 3 rows and 4 columns of random numbers between 0 and 1

array([[0.35408243, 0.32562086, 0.38833304, 0.0583294 ],
       [0.62039787, 0.67664994, 0.56042616, 0.98447091],
       [0.54066173, 0.65335849, 0.05406664, 0.69181572]])

In [35]:
# randn
np.random.randn(3,4) # 3 rows and 4 columns of random numbers from standard normal distribution

array([[ 0.10271247, -0.07192237,  0.30309197, -0.38868595],
       [ 1.7079503 , -0.13022303,  0.90107043, -1.92992094],
       [ 1.41421394,  0.68808426,  0.16816247,  0.64259468]])

In [36]:
# Randint
np.random.randint(10,20,(3,4))

array([[19, 16, 19, 15],
       [11, 17, 13, 17],
       [11, 13, 15, 10]], dtype=int32)

In [37]:
# Attibutes of Numpy Array
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Array:\n',arr)
print('Dimensions:',arr.ndim)
print('Shape:',arr.shape)
print('Size:',arr.size)
print('Data Type:',arr.dtype)
print('Item Size (in bytes):',arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimensions: 2
Shape: (3, 3)
Size: 9
Data Type: int64
Item Size (in bytes): 8


In [38]:
# array Slicing and Indexing
arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(arr.ndim)
arr

2


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [39]:
arr[0,2]

np.int64(3)

In [40]:
arr[:,2:]

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15]])

In [41]:
arr[1:,2:4]

array([[ 8,  9],
       [13, 14]])

In [42]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [43]:
arr_1d=np.array([1,2,3,4,5,6,7,8,9,10])
arr_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
arr_1d[3:8]

array([4, 5, 6, 7, 8])

In [45]:
np.random.randint(1,4,1)

array([2], dtype=int32)

In [46]:
arr=np.array([[1,2,3,4,5,12],[6,7,8,9,10,55],[11,12,13,14,15,77],[70,77,66,54,33,43]])
arr

array([[ 1,  2,  3,  4,  5, 12],
       [ 6,  7,  8,  9, 10, 55],
       [11, 12, 13, 14, 15, 77],
       [70, 77, 66, 54, 33, 43]])

In [47]:
# Numpy Vectorized Operations
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50]) 
# element wise addition
print('Addition:',arr1 + arr2)
# element wise subtraction
print('Subtraction:',arr2 - arr1)
# element wise multiplication
print('Multiplication:',arr1 * arr2)
# element wise division
print('Division:',arr2 / arr1)

Addition: [11 22 33 44 55]
Subtraction: [ 9 18 27 36 45]
Multiplication: [ 10  40  90 160 250]
Division: [10. 10. 10. 10. 10.]


In [48]:
# Implementation with 2D arrays
arr1_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2_2d=np.array([[10,20,30],[40,50,60],[70,80,90]])
print('2D Array 1:\n',arr1_2d)
print('2D Array 2:\n',arr2_2d)
# element wise addition
print('2D Addition:\n',arr1_2d + arr2_2d)

2D Array 1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
2D Array 2:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
2D Addition:
 [[11 22 33]
 [44 55 66]
 [77 88 99]]


In [49]:
# Universal Functions (ufuncs)
arr=np.array([1,2,3,4,5,9])
# square root
print('Square Root:',np.sqrt(arr))

# exponential
print('Exponential:',np.exp(arr))

# sine
print('Sine:',np.sin(arr))

# logarithm
print('Logarithm:',np.log(arr))

Square Root: [1.         1.41421356 1.73205081 2.         2.23606798 3.        ]
Exponential: [2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 8.10308393e+03]
Sine: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427  0.41211849]
Logarithm: [0.         0.69314718 1.09861229 1.38629436 1.60943791 2.19722458]


In [50]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
arr2=arr[3:7]
arr2

array([4, 5, 6, 7])

In [52]:
arr2[0]=100
arr2

array([100,   5,   6,   7])

In [53]:
arr

array([  1,   2,   3, 100,   5,   6,   7,   8,   9,  10])

In [54]:
arr3=arr.copy()
arr3

array([  1,   2,   3, 100,   5,   6,   7,   8,   9,  10])

In [55]:
# Statistical Operations for normalization 
# normalization means to have value mean 0 and standard deviation 1
data=np.array([1,2,3,4,5,6,7,8,9,10])

# calculate mean
mean=data.mean()

# calculate standard deviation
std=data.std()

# normalize the data
normalized_data=(data - mean)/std
print('Normalized Data:',normalized_data)

Normalized Data: [-1.5666989  -1.21854359 -0.87038828 -0.52223297 -0.17407766  0.17407766
  0.52223297  0.87038828  1.21854359  1.5666989 ]


In [ ]:
# calculate median mean standard deviation variance
data=np.array([1,2,3,4,5,6,7,8,9,10])

median=np.median(data)
mean=np.mean(data)
std=np.std(data)
variance=np.var(data)

print('Median:',median)
print('Mean:',mean) 
print('Standard Deviation:',std)
print('Variance:',variance)

Median: 5.5
Mean: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [61]:
# logical operation with numpy arrays
arr=np.array([10,20,30,40,50,60,70,80,90,100])
# elements greater than 50
print(arr[arr > 50])

arr[(arr > 50) & (arr < 90)]

[ 60  70  80  90 100]


array([60, 70, 80])

In [63]:
arr=np.array([10,20,30,40,50,60,70,80,90,100])


arr[arr>20]


array([ 30,  40,  50,  60,  70,  80,  90, 100])