# Numpy

In [1]:
! pip install numpy

In [2]:
# import the numpy library
import numpy as np

In [3]:
# create a numpy array
# numpy array format: np.array(list)
arr=np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))
print(arr.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [4]:
# create a 2d array
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d)
print(arr_2d.shape) # rows and columns

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [5]:
# rehsape a numpy array
arr=np.array([1, 2, 3, 4, 5]).reshape(1,5)
print(arr.shape)
print(arr)


(1, 5)
[[1 2 3 4 5]]


In [6]:
# Arnage
np.arange(start=2,stop=21,step=2).reshape(2,5)

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

In [7]:
np.zeros((3,4,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [8]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
# Identity Matrix
np.eye(5) # 4x4 identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
# Linspace
np.linspace(10,20,5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [11]:
# Random Numbers
np.random.rand(3,4) # 3 rows and 4 columns of random numbers between 0 and 1

array([[0.37410351, 0.51222241, 0.4528709 , 0.30404906],
       [0.44992729, 0.95656156, 0.31540291, 0.60726735],
       [0.25121186, 0.28974298, 0.80025749, 0.95018604]])

In [12]:
# randn
np.random.randn(3,4) # 3 rows and 4 columns of random numbers from standard normal distribution

array([[ 1.02791196, -0.06168082,  0.84923078,  0.06294347],
       [-0.8772078 , -1.46436943, -0.78254037, -2.86219381],
       [-0.62509546, -1.45469004,  0.72479367,  0.79281427]])

In [13]:
# Randint
np.random.randint(10,20,(3,4))

array([[16, 14, 16, 12],
       [12, 12, 17, 19],
       [15, 12, 19, 16]], dtype=int32)

In [14]:
# Attibutes of Numpy Array
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Array:\n',arr)
print('Dimensions:',arr.ndim)
print('Shape:',arr.shape)
print('Size:',arr.size)
print('Data Type:',arr.dtype)
print('Item Size (in bytes):',arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimensions: 2
Shape: (3, 3)
Size: 9
Data Type: int64
Item Size (in bytes): 8


In [15]:
# array Slicing and Indexing
arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(arr.ndim)
arr

2


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [16]:
arr[0,2]

np.int64(3)

In [17]:
arr[:,2:]

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15]])

In [18]:
arr[1:,2:4]

array([[ 8,  9],
       [13, 14]])

In [19]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [20]:
arr_1d=np.array([1,2,3,4,5,6,7,8,9,10])
arr_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
arr_1d[3:8]

array([4, 5, 6, 7, 8])

In [36]:
np.random.randint(1,4,1)

array([1], dtype=int32)

In [ ]:
random.rand and random.randn 

In [38]:
arr=np.array([[1,2,3,4,5,12],[6,7,8,9,10,55],[11,12,13,14,15,77],[70,77,66,54,33,43]])
arr

array([[ 1,  2,  3,  4,  5, 12],
       [ 6,  7,  8,  9, 10, 55],
       [11, 12, 13, 14, 15, 77],
       [70, 77, 66, 54, 33, 43]])

In [ ]:
# Numpy Vectorized Operations
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50]) 
# element wise addition
print('Addition:',arr1 + arr2)
# element wise subtraction
print('Subtraction:',arr2 - arr1)
# element wise multiplication
print('Multiplication:',arr1 * arr2)
# element wise division
print('Division:',arr2 / arr1)

Addition: [11 22 33 44 55]


In [42]:
# Implementation with 2D arrays
arr1_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2_2d=np.array([[10,20,30],[40,50,60],[70,80,90]])
print('2D Array 1:\n',arr1_2d)
print('2D Array 2:\n',arr2_2d)
# element wise addition
print('2D Addition:\n',arr1_2d + arr2_2d)

2D Array 1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
2D Array 2:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
2D Addition:
 [[11 22 33]
 [44 55 66]
 [77 88 99]]


In [ ]:
# Universal Functions (ufuncs)
arr=np.array([1,2,3,4,5,9])
# square root
print('Square Root:',np.sqrt(arr))

# exponential
print('Exponential:',np.exp(arr))

# sine
print('Sine:',np.sin(arr))

# logarithm
print('Logarithm:',np.log(arr))

Square Root: [1.         1.41421356 1.73205081 2.         2.23606798 3.        ]
Exponential: [2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 8.10308393e+03]
Sine: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427  0.41211849]
Logarithm: [0.         0.69314718 1.09861229 1.38629436 1.60943791 2.19722458]


In [50]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
arr2=arr[3:7]
arr2

array([4, 5, 6, 7])

In [55]:
arr2[0]=100
arr2

array([100,   5,   6,   7])

In [56]:
arr

array([  1,   2,   3, 100,   5,   6,   7,   8,   9,  10])

In [57]:
arr3=arr.copy()
arr3

array([  1,   2,   3, 100,   5,   6,   7,   8,   9,  10])